### ISSUE TITLE
Is it not possible to launch testnet node from blockheight 0?

### ISSUE THREAD

**Issue by APshenkin** [binance-chain/node-binary#115]
Trying to disable `state_sync_reactor` and `state_sync_height` for testnet, but then node crashes on start

```
panic: Failed to process committed block (2:41B358BC3AECCD5957414DB4AB435E844E65474CA9B01732F9F81CF7A6665FF9): Wrong Block.Header.AppHash.  Expected FAF374AC293B4CF88C1BF49499A425C0B348A3106287CDAC599CB7A79CAB0811, got 985E9C7761374CF2448E82CEA2CE4954302DB3AF94829A6DFD9982B2ED9CBA75
```

Also it's not possible to set state_sync_height in any value except 0. E.g. with 
`state_sync_height = 38520550`

End of logs
```
I[2019-09-12|14:31:25.403] added a peer to state sync reactor           module=statesync peer=2726550182cbc5f4618c27e49c730752a96901e8
I[2019-09-12|14:31:25.541] Stopping queryMaj23Routine for peer          module=consensus peer="Peer{MConn{52.200.132.60:27146} 8825b32e3abec71d772abf009ba1956d452be1fa out}"
I[2019-09-12|14:31:25.959] Stopping queryMaj23Routine for peer          module=consensus peer="Peer{MConn{52.200.132.60:27146} 8825b32e3abec71d772abf009ba1956d452be1fa out}"
I[2019-09-12|14:31:28.060] got enough peers to start state sync         module=statesync manifestHash="[100 117 109 109 121 104 97 115 104 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]" numOfPeers=4
I[2019-09-12|14:31:28.061] all peers we connected have no manifest, start fast sync directly module=statesync
I[2019-09-12|14:31:28.066] SwitchToBlockchain                           module=blockchain
I[2019-09-12|14:31:28.066] Starting BlockPool                           module=blockchain impl=BlockPool
I[2019-09-12|14:31:28.066] Stopping StatePool                           module=statesync impl=StatePool
I[2019-09-12|14:31:28.066] broadcast state status request               module=statesync
E[2019-09-12|14:31:28.212] Connection failed @ recvRoutine (reading byte) module=p2p peer=2726550182cbc5f4618c27e49c730752a96901e8@3.81.223.15:27146 conn=MConn{3.81.223.15:27146} err=EOF
E[2019-09-12|14:31:28.213] Stopping peer for error                      module=p2p peer="Peer{MConn{3.81.223.15:27146} 2726550182cbc5f4618c27e49c730752a96901e8 out}" err=EOF
I[2019-09-12|14:31:28.217] Stopping gossipDataRoutine for peer          module=consensus peer="Peer{MConn{3.81.223.15:27146} 2726550182cbc5f4618c27e49c730752a96901e8 out}"
I[2019-09-12|14:31:28.220] Stopping gossipVotesRoutine for peer         module=consensus peer="Peer{MConn{3.81.223.15:27146} 2726550182cbc5f4618c27e49c730752a96901e8 out}"
I[2019-09-12|14:31:28.616] No new orders for any pair, give up matching module=dexkeeper
I[2019-09-12|14:31:28.616] No order comes in for the block              module=dexkeeper
I[2019-09-12|14:31:28.676] added a peer to state sync reactor           module=statesync peer=2726550182cbc5f4618c27e49c730752a96901e8
panic: Failed to process committed block (2:41B358BC3AECCD5957414DB4AB435E844E65474CA9B01732F9F81CF7A6665FF9): Wrong Block.Header.AppHash.  Expected FAF374AC293B4CF88C1BF49499A425C0B348A3106287CDAC599CB7A79CAB0811, got 985E9C7761374CF2448E82CEA2CE4954302DB3AF94829A6DFD9982B2ED9CBA75

goroutine 1073 [running]:
github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/blockchain.(*BlockchainReactor).poolRoutine(0xc0002669c0)
	/Users/huangsuyu/go/src/github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/blockchain/reactor.go:372 +0x1874
created by github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/blockchain.(*BlockchainReactor).SwitchToBlockchain
	/Users/huangsuyu/go/src/github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/blockchain/reactor.go:144 +0x326
```

So maybe there are some archived snapshots for node that we can download directly?

**Comment by huangsuyu** [comment]
hello, @APshenkin 

can you please share your `config.toml`?

If your node was already synced, it will switch to fast sync automatically.

**Comment by APshenkin** [comment]
Hi @huangsuyu 

Here is my current config:

<details>
  <summary>config.toml</summary>

```
# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

##### main base config options #####

# TCP or UNIX socket address of the ABCI application,
# or the name of an ABCI application compiled in with the Tendermint binary
proxy_app = "tcp://127.0.0.1:28658"

# A custom human readable name for this node
moniker = "xxx"

# If this node is many blocks behind the tip of the chain, FastSync
# allows them to catchup quickly by downloading blocks in parallel
# and verifying their commits
fast_sync = true

# As state sync is an experimental feature, this switch can totally disable it on core network nodes (validator, witness)
state_sync_reactor = true

# If this node is many days behind the tip of the chain, StateSyncHeight
# allows them to catchup quickly by downloading app state (without historical blocks)
# in parallel and start syncing block afterwards
# <0 - turn off state sync
# =0 - sync from peer's latest height
# >0 - sync from that height
state_sync_height = 0

# Database backend: leveldb | memdb | cleveldb
db_backend = "leveldb"

# Database directory
db_dir = "data"

# Output level for logging, including package level options
log_level = "statesync:error,blockchain:error,main:error,paramHub:error,dex:error,dexkeeper:error,state:error,token:error,pub:error,consensus:error,*:error"

# Output format: 'plain' (colored text) or 'json'
log_format = "plain"

##### additional base config options #####

# Path to the JSON file containing the initial validator set and other meta data
genesis_file = "config/genesis.json"

# Path to the JSON file containing the private key to use as a validator in the consensus protocol
priv_validator_key_file = "config/priv_validator_key.json"

# Path to the JSON file containing the last sign state of a validator
priv_validator_state_file = "data/priv_validator_state.json"

# TCP or UNIX socket address for Tendermint to listen on for
# connections from an external PrivValidator process
priv_validator_laddr = ""

# Path to the JSON file containing the private key to use for node authentication in the p2p protocol
node_key_file = "config/node_key.json"

# Mechanism to connect to the ABCI application: socket | grpc
abci = "socket"

# TCP or UNIX socket address for the profiling server to listen on
prof_laddr = ":9060"

# If true, query the ABCI app on connecting to a new peer
# so the app can decide if we should keep the connection or not
filter_peers = false

# If false, will not check appHash when apply block
with_app_stat = true

##### advanced configuration options #####

##### rpc server configuration options #####
[rpc]

# TCP or UNIX socket address for the RPC server to listen on
laddr = "tcp://0.0.0.0:26657"

# A list of origins a cross-domain request can be executed from
# Default value '[]' disables cors support
# Use '["*"]' to allow any origin
cors_allowed_origins = []

# A list of methods the client is allowed to use with cross-domain requests
cors_allowed_methods = ["HEAD", "GET", "POST", ]

# A list of non simple headers the client is allowed to use with cross-domain requests
cors_allowed_headers = ["Origin", "Accept", "Content-Type", "X-Requested-With", "X-Server-Time", ]

# TCP or UNIX socket address for the gRPC server to listen on
# NOTE: This server only supports /broadcast_tx_commit
grpc_laddr = ""

# Maximum number of simultaneous connections.
# Does not include RPC (HTTP&WebSocket) connections. See max_open_connections
# If you want to accept a larger number than the default, make sure
# you increase your OS limits.
# 0 - unlimited.
# Should be < {ulimit -Sn} - {MaxNumInboundPeers} - {MaxNumOutboundPeers} - {N of wal, db and other open files}
# 1024 - 40 - 10 - 50 = 924 = ~900
grpc_max_open_connections = 900

# Activate unsafe RPC commands like /dial_seeds and /unsafe_flush_mempool
unsafe = false

# Maximum number of simultaneous connections (including WebSocket).
# Does not include gRPC connections. See grpc_max_open_connections
# If you want to accept a larger number than the default, make sure
# you increase your OS limits.
# 0 - unlimited.
# Should be < {ulimit -Sn} - {MaxNumInboundPeers} - {MaxNumOutboundPeers} - {N of wal, db and other open files}
# 1024 - 40 - 10 - 50 = 924 = ~900
max_open_connections = 900


# Maximum number of go routine to process websocket request.
# 1 - process websocket request synchronously.
# 10 - default size.
# Should be {WebsocketPoolSpawnSize} =< {WebsocketPoolMaxSize}
websocket_pool_size = 10

# The queued buffer for workers to process requests.
# 10 -default
websocket_pool_queue_size = 10

# The initial size of goroutines in pool.
# 1 - process websocket request synchronously.
# 5 - default size
# Should be {WebsocketPoolSpawnSize} =< {WebsocketPoolMaxSize}
websocket_pool_spawn_size = 5

# Maximum number of unique clientIDs that can /subscribe
# If you're using /broadcast_tx_commit, set to the estimated maximum number
# of broadcast_tx_commit calls per block.
max_subscription_clients = 100

# Maximum number of unique queries a given client can /subscribe to
# If you're using GRPC (or Local RPC client) and /broadcast_tx_commit, set to
# the estimated # maximum number of broadcast_tx_commit calls per block.
max_subscriptions_per_client = 5

# How long to wait for a tx to be committed during /broadcast_tx_commit.
# WARNING: Using a value larger than 10s will result in increasing the
# global HTTP write timeout, which applies to all connections and endpoints.
# See https://github.com/tendermint/tendermint/issues/3435
timeout_broadcast_tx_commit = "10s"

# The name of a file containing certificate that is used to create the HTTPS server.
# If the certificate is signed by a certificate authority,
# the certFile should be the concatenation of the server's certificate, any intermediates,
# and the CA's certificate.
# NOTE: both tls_cert_file and tls_key_file must be present for Tendermint to create HTTPS server. Otherwise, HTTP server is run.
tls_cert_file = ""

# The name of a file containing matching private key that is used to create the HTTPS server.
# NOTE: both tls_cert_file and tls_key_file must be present for Tendermint to create HTTPS server. Otherwise, HTTP server is run.
tls_key_file = ""

##### peer to peer configuration options #####
[p2p]

# Address to listen for incoming connections
laddr = "tcp://0.0.0.0:26656"

# Address to advertise to peers for them to dial
# If empty, will use the same port as the laddr,
# and will introspect on the listener or use UPnP
# to figure out the address.
external_address = ""

# Comma separated list of seed nodes to connect to
seeds = ""

# Comma separated list of nodes to keep persistent connections to
persistent_peers = "2726550182cbc5f4618c27e49c730752a96901e8@a41086771245011e988520ad55ba7f5a-5f7331395e69b0f3.elb.us-east-1.amazonaws.com:27146,381934b9b3f862d1e81e699d8e1d38929f330cef@aa13359cd244f11e988520ad55ba7f5a-c3963b80c9b991b7.elb.us-east-1.amazonaws.com:27146,fe5eb5a945598476abe4826a8d31b9f8da7b1a54@aa35ed7c1244f11e988520ad55ba7f5a-bbfb4fe79dee5d7e.elb.us-east-1.amazonaws.com:27146,8825b32e3abec71d772abf009ba1956d452be1fa@aa58a7e44244f11e988520ad55ba7f5a-45d504e63bacb8dd.elb.us-east-1.amazonaws.com:27146,9612b570bffebecca4776cb4512d08e252119005@a0b88b324243a11e994280efee3352a7-96b6996626c6481d.elb.ap-northeast-1.amazonaws.com:27146,8c379d4d3b9995c712665dc9a9414dbde5b30483@aa1e4d0d1243a11e9a951063f6065739-7a82be90a58744b6.elb.ap-northeast-1.amazonaws.com:27146,7156d461742e2a1e569fd68426009c4194830c93@aa841c226243a11e9a951063f6065739-eee556e439dc6a3b.elb.ap-northeast-1.amazonaws.com:27146"
# UPNP port forwarding
upnp = false

# Path to address book
addr_book_file = "config/addrbook.json"

# Set true for strict address routability rules
# Set false for private or local networks
addr_book_strict = false

# Maximum number of inbound peers
max_num_inbound_peers = 40

# Maximum number of outbound peers to connect to, excluding persistent peers
max_num_outbound_peers = 10

# Time to wait before flushing messages out on the connection
flush_throttle_timeout = "10ms"

# Maximum size of a message packet payload, in bytes
max_packet_msg_payload_size = 10485760

# Maximum num of keys a state sync request ask for
keys_per_request = 1500

# Rate at which packets can be sent, in bytes/second
send_rate = 52428800

# Rate at which packets can be received, in bytes/second
recv_rate = 102428800

# Interval to send pings
ping_interval = "10m0s"

# Maximum wait time for pongs
pong_timeout = "450s"

# Set true to enable the peer-exchange reactor
pex = true

# Seed mode, in which node constantly crawls the network and looks for
# peers. If another node asks it for addresses, it responds and disconnects.
#
# Does not work if the peer-exchange reactor is disabled.
seed_mode = false

# Comma separated list of peer IDs to keep private (will not be gossiped to other peers)
private_peer_ids = ""

# Toggle to disable guard against peers connecting from the same ip.
allow_duplicate_ip = true

# Peer connection configuration.
handshake_timeout = "20s"
dial_timeout = "3s"

##### mempool configuration options #####
[mempool]

recheck = true
broadcast = true
wal_dir = ""

# Maximum number of transactions in the mempool
size = 5000

# Limit the total size of all txs in the mempool.
# This only accounts for raw transactions (e.g. given 1MB transactions and
# max_txs_bytes=5MB, mempool will only accept 5 transactions).
max_txs_bytes = 1073741824

# Size of the cache (used to filter transactions we saw earlier) in transactions
cache_size = 10000

##### consensus configuration options #####
[consensus]

wal_file = "data/cs.wal/wal"

timeout_propose = "3s"
timeout_propose_delta = "500ms"
timeout_prevote = "1s"
timeout_prevote_delta = "500ms"
timeout_precommit = "1s"
timeout_precommit_delta = "500ms"
timeout_commit = "1s"

# Make progress as soon as we have all the precommits (as if TimeoutCommit = 0)
skip_timeout_commit = true

# EmptyBlocks mode and possible interval between empty blocks
create_empty_blocks = true
create_empty_blocks_interval = "0s"

# Reactor sleep duration parameters
peer_gossip_sleep_duration = "10ms"
peer_query_maj23_sleep_duration = "2s"

# Block time parameters. Corresponds to the minimum time increment between consecutive blocks.
blocktime_iota = "0s"

##### transactions indexer configuration options #####
[tx_index]

# What indexer to use for transactions
#
# Options:
#   1) "null"
#   2) "kv" (default) - the simplest possible indexer, backed by key-value storage (defaults to levelDB; see DBBackend).
indexer = "kv"

# Comma-separated list of tags to index (by default the only tag is "tx.hash")
#
# You can also index transactions by height by adding "tx.height" tag here.
#
# It's recommended to index only a subset of tags due to possible memory
# bloat. This is, of course, depends on the indexer's DB and the volume of
# transactions.
index_tags = ""

# When set to true, tells indexer to index all tags (predefined tags:
# "tx.hash", "tx.height" and all tags from DeliverTx responses).
#
# Note this may be not desirable (see the comment above). IndexTags has a
# precedence over IndexAllTags (i.e. when given both, IndexTags will be
# indexed).
index_all_tags = false

##### block indexer configuration options #####
[block_index]

# What indexer to use for blocks
#
# Options:
#   1) "null"
#   2) "kv" (default) - the simplest possible indexer, backed by key-value storage (defaults to levelDB; see DBBackend).
indexer = "null"

##### instrumentation configuration options #####
[instrumentation]

# When true, Prometheus metrics are served under /metrics on
# PrometheusListenAddr.
# Check out the documentation for the list of available metrics.
prometheus = false

# Address to listen for Prometheus collector(s) connections
prometheus_listen_addr = ":28660"

# Maximum number of simultaneous connections.
# If you want to accept a larger number than the default, make sure
# you increase your OS limits.
# 0 - unlimited.
max_open_connections = 3

# Instrumentation namespace
namespace = "tendermint"
```

</details>

I had launched testnet with this config 12 th September, but testnet is still not synced

`/status` returns:

```
{
  "jsonrpc": "2.0",
  "id": "",
  "result": {
    "node_info": {
      "protocol_version": {
        "p2p": "7",
        "block": "10",
        "app": "0"
      },
      "id": "8b9c56b383393e2383682daecde811787cce0499",
      "listen_addr": "tcp://0.0.0.0:26656",
      "network": "Binance-Chain-Nile",
      "version": "0.31.5",
      "channels": "364020212223303800",
      "moniker": "xxx",
      "other": {
        "tx_index": "on",
        "rpc_address": "tcp://0.0.0.0:26657"
      }
    },
    "sync_info": {
      "latest_block_hash": "746F3E4843395E76E71AFCA386D9946946EB277738508DCB4B15C472F96C8B4B",
      "latest_app_hash": "C969F2BC82BF3291EB961C1988BF372EF5D860CBD130928C296B7508BF91AA8E",
      "latest_block_height": "39037656",
      "latest_block_time": "2019-09-13T10:57:57.042701993Z",
      "catching_up": true
    },
    "validator_info": {
      "address": "3AD1BF57985DDCB983C53BE6B6B218F77E57A813",
      "pub_key": {
        "type": "tendermint/PubKeyEd25519",
        "value": "WeFOqHa30R1vKSrzejRiS6aGkMnEm0vVCsRIacGrvQ0="
      },
      "voting_power": "0"
    }
  }
}
```


Also there is a lot of errors in logs like:
```
E[2019-09-16|07:57:46.899] Stopping peer for error                      module=p2p peer="Peer{MConn{34.238.37.238:27146} 8825b32e3abec71d772abf009ba1956d452be1fa out}" err=EOFE[2019-09-16|07:57:47.158] Stopping peer for error                      module=p2p peer="Peer{MConn{34.238.37.238:27146} 8825b32e3abec71d772abf009ba1956d452be1fa out}" err=EOF
E[2019-09-16|07:57:47.158] Connection failed @ recvRoutine (reading byte) module=p2p peer=8825b32e3abec71d772abf009ba1956d452be1fa@34.238.37.238:27146 conn=MConn{34.238.37.238:27146} err=EOF
```


Also before launch I tried to play with options `state_sync_reactor` and `state_sync_height`

With 
```
state_sync_reactor = false
state_sync_height = -1
```

Node crashes after launch

With 
```
state_sync_reactor = true
state_sync_height = 38520550
```

it also crashes.

So currently it's impossible in testnet to:
1. Start node without state_sync (so you can't get all testnet state)
2. Launch node with state_sync with certain block height
3. Sync node with state_sync = 0 and sync node

**Comment by ackratos** [comment]
> So currently it's impossible in testnet to:
> 
> 1. Start node without state_sync (so you can't get all testnet state)
> 2. Launch node with state_sync with certain block height
> 3. Sync node with state_sync = 0 and sync node

1. yes. testnet hard forked at height 2. You have to state sync to catch up. (but mainnet support sync from height 1)
2. yes. Binancechain only take a syncable snapshot once a day, you have to specify that particular height
3. I don't know what's your original error when you saw status shows:
```
{
  "jsonrpc": "2.0",
  "id": "",
  "result": {
    "node_info": {
      "protocol_version": {
        "p2p": "7",
        "block": "10",
        "app": "0"
      },
      "id": "8b9c56b383393e2383682daecde811787cce0499",
      "listen_addr": "tcp://0.0.0.0:26656",
      "network": "Binance-Chain-Nile",
      "version": "0.31.5",
      "channels": "364020212223303800",
      "moniker": "xxx",
      "other": {
        "tx_index": "on",
        "rpc_address": "tcp://0.0.0.0:26657"
      }
    },
    "sync_info": {
      "latest_block_hash": "746F3E4843395E76E71AFCA386D9946946EB277738508DCB4B15C472F96C8B4B",
      "latest_app_hash": "C969F2BC82BF3291EB961C1988BF372EF5D860CBD130928C296B7508BF91AA8E",
      "latest_block_height": "39037656",
```

This status response indicates you have synced to height "39037656", while the crash panic log you pasted indicates you crash at height 2:
```
panic: Failed to process committed block (2:41B358BC3AECCD5957414DB4AB435E844E65474CA9B01732F9F81CF7A6665FF9): Wrong Block.Header.AppHash.  Expected FAF374AC293B4CF88C1BF49499A425C0B348A3106287CDAC599CB7A79CAB0811, got 985E9C7761374CF2448E82CEA2CE4954302DB3AF94829A6DFD9982B2ED9CBA75
```

Did you set the correct bnbchaind home directory when you start node after your first success state sync?
If you don't want figure out how you reached this messy situation, you could follow instructions:
```
If full node has already started, suggested way is to delete the (after backup) $BNCHOME/data directory and $BNCHOME/config/priv_validator_key.json before enabling state sync.
```

**Comment by APshenkin** [comment]
Hi, @ackratos !

> This status response indicates you have synced to height "39037656", while the crash panic log you pasted indicates you crash at height 2:

Yes, panic log was from case, when try to run 
```
state_sync_reactor = false
state_sync_height = -1
```

or

```
state_sync_reactor = true
state_sync_height = 38520550
```



When running 
```
state_sync_reactor = true
state_sync_height = 0
```

It start syncing, but it can't catch up. Syncing is too slow (1 block per second) and also there is a lot of logs like

```
E[2019-09-16|07:57:46.899] Stopping peer for error                      module=p2p peer="Peer{MConn{34.238.37.238:27146} 8825b32e3abec71d772abf009ba1956d452be1fa out}" err=EOFE[2019-09-16|07:57:47.158] Stopping peer for error                      module=p2p peer="Peer{MConn{34.238.37.238:27146} 8825b32e3abec71d772abf009ba1956d452be1fa out}" err=EOF
E[2019-09-16|07:57:47.158] Connection failed @ recvRoutine (reading byte) module=p2p peer=8825b32e3abec71d772abf009ba1956d452be1fa@34.238.37.238:27146 conn=MConn{34.238.37.238:27146} err=EOF
```

BTW with mainnet everything works fine (syncing completes very fast and no errors)



Any way it would be great, if there will be archive with all testnet data, that we can use to launch testnet node with complete state (all blocks and transactions)

Is it possible to upload this archive somewhere?

**Comment by huangsuyu** [comment]
@APshenkin 

it can be hard to share any blockchain data because you need to trust its source
