### ISSUE TITLE
启动节点报错

### ISSUE THREAD

**Issue by ViolainOt** [binance-chain/node-binary#184]
按照这个文档的方法[https://docs.binance.org/fullnode.html]操作，config放在了～/.bnbchaind下，启动命令 `./bnbchaind start` 执行报错，错误信息
`./bnbchaind: line 1: version: command not found
./bnbchaind: line 2: oid: command not found
/Library/Developer/CommandLineTools/usr/bin/size: 45160816 No such file or directory`

**Comment by huangsuyu** [comment]
你好！
本地bianry文件没有下载完整。所有binary都以`git lfs`存储。
请按照readme指令操作。https://github.com/binance-chain/node-binary/blob/master/README.md

**Comment by ViolainOt** [comment]
> 你好！
> 本地bianry文件没有下载完整。所有binary都以`git lfs`存储。
> 请按照readme指令操作。https://github.com/binance-chain/node-binary/blob/master/README.md
是的没错，我重新下载了可以运行了，但是./bnbchaind start运行执行同步区块是从最新块开始的，我用curl localhost:27147/block?height=1 查询第一块的信息是没有的，怎么设置同步所有区块

**Comment by ViolainOt** [comment]
还有个几个问题望解答，1、我在服务器上跑的这个节点，我本地可以通过 服务器ip:端口/status 获取信息吗，是否需要其他设置  2、有没有个接口可以获取指定区块的交易，我看文档里没有说清楚 3、怎么通过节点获取区块奖励给哪个地址了

**Comment by huangsuyu** [comment]
> 是的没错，我重新下载了可以运行了，但是./bnbchaind start运行执行同步区块是从最新块开始的，我用curl localhost:27147/block?height=1 查询第一块的信息是没有的，怎么设置同步所有区块
> 
> > 你好！
> > 本地bianry文件没有下载完整。所有binary都以`git lfs`存储。
> > 请按照readme指令操作。https://github.com/binance-chain/node-binary/blob/master/README.md

为了让节点尽快同步，默认的同步方式是`state-sync`. 该同步方式不会从头开始同步。文档：https://docs.binance.org/fullnode.html#state-sync

**Comment by huangsuyu** [comment]
> 还有个几个问题望解答，1、我在服务器上跑的这个节点，我本地可以通过 服务器ip:端口/status 获取信息吗，是否需要其他设置 2、有没有个接口可以获取指定区块的交易，我看文档里没有说清楚 3、怎么通过节点获取区块奖励给哪个地址了

1. 请求status请参考对应的rpc端口：https://docs.binance.org/api-reference/node-rpc.html
2. https://docs.binance.org/api-reference/dex-api/paths.html#apiv2transactions-in-blockblockheight
3. 通过配置kafka可以查看block fee 信息： https://docs.binance.org/get-extra-data-from-fullnode.html

**Comment by ViolainOt** [comment]
> > 还有个几个问题望解答，1、我在服务器上跑的这个节点，我本地可以通过 服务器ip:端口/status 获取信息吗，是否需要其他设置 2、有没有个接口可以获取指定区块的交易，我看文档里没有说清楚 3、怎么通过节点获取区块奖励给哪个地址了
> 
> 1. 请求status请参考对应的rpc端口：https://docs.binance.org/api-reference/node-rpc.html
> 2. https://docs.binance.org/api-reference/dex-api/paths.html#apiv2transactions-in-blockblockheight
> 3. 通过配置kafka可以查看block fee 信息： https://docs.binance.org/get-extra-data-from-fullnode.html

第二个不能通过我自己搭建的全节点获取吗，你给的链接是通过api获取，官方api请求是有限制的呀

**Comment by huangsuyu** [comment]
你也可以本地解析每个区块中的数据。

**Comment by ViolainOt** [comment]
> 你也可以本地解析每个区块中的数据。

具体怎么解析有代码示例吗，我看python-sdk里面是没有解析区块数据相关代码的

**Comment by ViolainOt** [comment]
> > 是的没错，我重新下载了可以运行了，但是./bnbchaind start运行执行同步区块是从最新块开始的，我用curl localhost:27147/block?height=1 查询第一块的信息是没有的，怎么设置同步所有区块
> > > 你好！
> > > 本地bianry文件没有下载完整。所有binary都以`git lfs`存储。
> > > 请按照readme指令操作。https://github.com/binance-chain/node-binary/blob/master/README.md
> 
> 为了让节点尽快同步，默认的同步方式是`state-sync`. 该同步方式不会从头开始同步。文档：https://docs.binance.org/fullnode.html#state-sync

能说下怎么设置才能从1块开始同步吗，文档里面好多参数代码里面都是没有的，我用的是0.6.3-hotfix版本

**Comment by huangsuyu** [comment]
@ViolainOt 请参考文档： https://docs.binance.org/fullnode.html#config-syncing
使用`fast-sync`就可以从block#1同步

**Comment by ViolainOt** [comment]
同步区块报错  
`panic: Failed to process committed block (1082014:39C2F09916BD3415C40BD825406C09A022C98FFCDBDFFFC7DADA0E822F60F6B9): Wrong Block.Header.AppHash.  Expected AC9FAC16513AF96A38822F2DF9276131D6ABDCD9EF47A6EEDACF5CA3E54883C0, got 92EB0FF45ED3F1EDD8A30829C2712EF5DFA7F09A2F83B24AC330A2BF5B14BE9E

goroutine 1993 [running]:
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc000bf49c0)
        /home/suyu/go/pkg/mod/github.com/binance-chain/bnc-tendermint@v0.32.3-binance.1/blockchain/v0/reactor.go:399 +0x1bf0
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).SwitchToBlockchain
        /home/suyu/go/pkg/mod/github.com/binance-chain/bnc-tendermint@v0.32.3-binance.1/blockchain/v0/reactor.go:153 +0x326`

再次启动还是报错
`ERROR: error during handshake: error on replay: Wrong Block.Header.AppHash.  Expected AC9FAC16513AF96A38822F2DF9276131D6ABDCD9EF47A6EEDACF5CA3E54883C0, got 92EB0FF45ED3F1EDD8A30829C2712EF5DFA7F09A2F83B24AC330A2BF5B14BE9E`

这个情况出现了两次，之前同步也是出现了这个问题， 然后我删除区块数据重新跑的，又出现了这个问题
用的fullnone linux 0.6.3-hotfix版本 使用的fast_sync, block修改为了#1

**Comment by huangsuyu** [comment]
> 同步区块报错
> 
> ```
> panic: Failed to process committed block (1082014:39C2F09916BD3415C40BD825406C09A022C98FFCDBDFFFC7DADA0E822F60F6B9): Wrong Block.Header.AppHash.  Expected AC9FAC16513AF96A38822F2DF9276131D6ABDCD9EF47A6EEDACF5CA3E54883C0, got 92EB0FF45ED3F1EDD8A30829C2712EF5DFA7F09A2F83B24AC330A2BF5B14BE9E
> 
> goroutine 1993 [running]:
> github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc000bf49c0)
>         /home/suyu/go/pkg/mod/github.com/binance-chain/bnc-tendermint@v0.32.3-binance.1/blockchain/v0/reactor.go:399 +0x1bf0
> created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).SwitchToBlockchain
>         /home/suyu/go/pkg/mod/github.com/binance-chain/bnc-tendermint@v0.32.3-binance.1/blockchain/v0/reactor.go:153 +0x326
> ```
> 
> 再次启动还是报错
> `ERROR: error during handshake: error on replay: Wrong Block.Header.AppHash. Expected AC9FAC16513AF96A38822F2DF9276131D6ABDCD9EF47A6EEDACF5CA3E54883C0, got 92EB0FF45ED3F1EDD8A30829C2712EF5DFA7F09A2F83B24AC330A2BF5B14BE9E`
> 
> 这个情况出现了两次，之前同步也是出现了这个问题， 然后我删除区块数据重新跑的，又出现了这个问题
> 用的fullnone linux 0.6.3-hotfix版本 使用的fast_sync, block修改为了#1

你好，@ViolainOt  请问block修改了什么？ 能提供详细配置吗？
谢谢！

**Comment by ViolainOt** [comment]
> > 同步区块报错
> > ```
> > panic: Failed to process committed block (1082014:39C2F09916BD3415C40BD825406C09A022C98FFCDBDFFFC7DADA0E822F60F6B9): Wrong Block.Header.AppHash.  Expected AC9FAC16513AF96A38822F2DF9276131D6ABDCD9EF47A6EEDACF5CA3E54883C0, got 92EB0FF45ED3F1EDD8A30829C2712EF5DFA7F09A2F83B24AC330A2BF5B14BE9E
> > 
> > goroutine 1993 [running]:
> > github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc000bf49c0)
> >         /home/suyu/go/pkg/mod/github.com/binance-chain/bnc-tendermint@v0.32.3-binance.1/blockchain/v0/reactor.go:399 +0x1bf0
> > created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).SwitchToBlockchain
> >         /home/suyu/go/pkg/mod/github.com/binance-chain/bnc-tendermint@v0.32.3-binance.1/blockchain/v0/reactor.go:153 +0x326
> > ```
> > 
> > 
> > 再次启动还是报错
> > `ERROR: error during handshake: error on replay: Wrong Block.Header.AppHash. Expected AC9FAC16513AF96A38822F2DF9276131D6ABDCD9EF47A6EEDACF5CA3E54883C0, got 92EB0FF45ED3F1EDD8A30829C2712EF5DFA7F09A2F83B24AC330A2BF5B14BE9E`
> > 这个情况出现了两次，之前同步也是出现了这个问题， 然后我删除区块数据重新跑的，又出现了这个问题
> > 用的fullnone linux 0.6.3-hotfix版本 使用的fast_sync, block修改为了#1
> 
> 你好，@ViolainOt 请问block修改了什么？ 能提供详细配置吗？
> 谢谢！

只修改了 0.6.3-hotfix/config/config.toml 中的 state_sync_height = 1（本来是0）

**Comment by huangsuyu** [comment]
@ViolainOt 你好，请按照文档重的说明，将state_sync_height设为-1。

**Comment by ViolainOt** [comment]
> @ViolainOt 你好，请按照文档重的说明，将state_sync_height设为-1。

按照你说的，修改完之后重新同步的，同步了没多久又异常了
`panic: Failed to process committed block (1082014:39C2F09916BD3415C40BD825406C09A022C98FFCDBDFFFC7DADA0E822F60F6B9): Wrong Block.Header.AppHash.  Expected AC9FAC16513AF96A38822F2DF9276131D6ABDCD9EF47A6EEDACF5CA3E54883C0, got 92EB0FF45ED3F1EDD8A30829C2712EF5DFA7F09A2F83B24AC330A2BF5B14BE9E

goroutine 220 [running]:
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc000cd9860)
        /home/suyu/go/pkg/mod/github.com/binance-chain/bnc-tendermint@v0.32.3-binance.1/blockchain/v0/reactor.go:399 +0x1bf0
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
        /home/suyu/go/pkg/mod/github.com/binance-chain/bnc-tendermint@v0.32.3-binance.1/blockchain/v0/reactor.go:126 +0x84`

再次启动还是报错
`ERROR: error during handshake: error on replay: Wrong Block.Header.AppHash.  Expected AC9FAC16513AF96A38822F2DF9276131D6ABDCD9EF47A6EEDACF5CA3E54883C0, got 92EB0FF45ED3F1EDD8A30829C2712EF5DFA7F09A2F83B24AC330A2BF5B14BE9E`

**Comment by ViolainOt** [comment]
> @ViolainOt 你好，请按照文档重的说明，将state_sync_height设为-1。

你好 可以发个联系方式到我邮箱吗 violainOt@gmail.com 可以给你截图看看问题，这样交流效率太低了

**Comment by huangsuyu** [comment]
> [violainOt@gmail.com](mailto:violainOt@gmail.com)

已经发送！

**Comment by huangsuyu** [comment]
@ViolainOt 

请尝试用recover工具回滚到上一个块。https://github.com/binance-chain/node-binary/tree/master/tools/recover
```
state_recover 1082013 {path-to-home}
```
