### ISSUE TITLE
panic: StoreBlockHeight (65900358) > StateBlockHeight + 1 (1)

### ISSUE THREAD

**Issue by senhanxiao** [binance-chain/node-binary#186]
ubuntu@bdes-bn:~/0.6.3-hotfix/linux$ panic: StoreBlockHeight (65900358) > StateBlockHeight + 1 (1)

goroutine 1 [running]:
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc000b41680, 0xa, 0x0, 0xc000a63040, 0x6, 0xc000a64940, 0x12, 0x0, 0x0, 0x0, ...)
        /home/suyu/go/pkg/mod/github.com/binance-chain/bnc-tendermint@v0.32.3-binance.1/consensus/replay.go:355 +0x16e6
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc000b41680, 0x192d600, 0xc000a350a0, 0x149a180, 0x41d313)
        /home/suyu/go/pkg/mod/github.com/binance-chain/bnc-tendermint@v0.32.3-binance.1/consensus/replay.go:271 +0x61e
github.com/tendermint/tendermint/node.doHandshake(0x192b080, 0xc000011568, 0xa, 0x0, 0xc000a63040, 0x6, 0xc000a64940, 0x12, 0x0, 0x0, ...)
        /home/suyu/go/pkg/mod/github.com/binance-chain/bnc-tendermint@v0.32.3-binance.1/node/node.go:313 +0x211
github.com/tendermint/tendermint/node.NewNode(0xc0000b0f20, 0x190a520, 0xc000cddea0, 0xc003e448b0, 0x18ea320, 0xc000c059f0, 0xc003e44b30, 0x172c1d0, 0xc003e44b40, 0x1912660, ...)
        /home/suyu/go/pkg/mod/github.com/binance-chain/bnc-tendermint@v0.32.3-binance.1/node/node.go:649 +0x497
github.com/cosmos/cosmos-sdk/server.startInProcess(0xc000ac9cc0, 0x172cb80, 0x1d, 0x0, 0x0)
        /home/suyu/go/pkg/mod/github.com/binance-chain/bnc-cosmos-sdk@v0.25.0-binance.21/server/start.go:133 +0x57e
github.com/cosmos/cosmos-sdk/server.StartCmd.func1(0xc000cd9400, 0x2725bf0, 0x0, 0x0, 0x0, 0x0)
        /home/suyu/go/pkg/mod/github.com/binance-chain/bnc-cosmos-sdk@v0.25.0-binance.21/server/start.go:44 +0xb5
github.com/spf13/cobra.(*Command).execute(0xc000cd9400, 0x2725bf0, 0x0, 0x0, 0xc000cd9400, 0x2725bf0)
        /home/suyu/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x465
github.com/spf13/cobra.(*Command).ExecuteC(0xc00011a500, 0x2, 0xc000ac9f20, 0x15bca4a)
        /home/suyu/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
        /home/suyu/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc00011a500, 0x172cf98, 0x2, 0xc000c8da80)
        /home/suyu/go/pkg/mod/github.com/binance-chain/bnc-tendermint@v0.32.3-binance.1/libs/cli/setup.go:89 +0x3c
main.main()
        /home/suyu/go/src/github.com/binance-chain/node/cmd/bnbchaind/main.go:54 +0x3ef

**Comment by senhanxiao** [comment]
我真是服了，节点数据全删了，重新再同步，又出现panic: StoreBlockHeight (65900358) > StateBlockHeight + 1 (1)
真想知道有人将testnet 节点同步成功的吗
