### ISSUE TITLE
Lightd client cannot connect to dataseed1.binance.org

### ISSUE THREAD

**Issue by xana-rahmani** [binance-chain/node-binary#197]
When I use this command:
`./lightd --chain-id "Binance-Chain-Tigris" --node tcp://dataseed1.binance.org:80 --home-dir .bnb`

I get this result:
```
I[2020-02-22|18:49:57.762] Connecting to source HTTP client...          
I[2020-02-22|18:49:57.763] Constructing Verifier...                     
I[2020-02-22|18:49:57.763] lite/proxy/NewVerifier()...                  module=lite/proxy chainID=Binance-Chain-Tigris rootDir=.bnb client=WSEvents
I[2020-02-22|18:49:57.972] DBProvider.LatestFullCommit()...             module=lite label=trusted.mem chainID=Binance-Chain-Tigris minHeight=1 maxHeight=9223372036854775807
I[2020-02-22|18:49:57.972] DBProvider.LatestFullCommit()...             module=lite label=trusted.lvl chainID=Binance-Chain-Tigris minHeight=1 maxHeight=9223372036854775807
I[2020-02-22|18:49:57.972] lite/proxy/NewVerifier found no trusted full commit, initializing from source from height 1... module=lite/proxy 
Error: Status: Error unmarshalling rpc response <html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
</body>
</html>
, error invalid character '<' looking for beginning of value
panic: Status: Error unmarshalling rpc response <html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
</body>
</html>
, error invalid character '<' looking for beginning of value

goroutine 1 [running]:
main.main()
	/Users/huangsuyu/go/src/github.com/binance-chain/node/cmd/lightd/main.go:22 +0x5b
```

**Comment by huangsuyu** [comment]
Hello,

There was a network issue with `dataseed1` yesterday and all is recovered now. 
Please retry with other dataseed available, you can try those:
https://dataseed2.ninicoin.io/
https://dataseed3.binance.org/
https://dataseed4.binance.org/

**Comment by xana-rahmani** [comment]
I tested the following command but again encountered the previous error.

`./lightd --chain-id "Binance-Chain-Tigris" --node tcp://dataseed2.ninicoin.io:80`
`./lightd --chain-id "Binance-Chain-Tigris" --node tcp://dataseed3.binance.org:80`
`./lightd --chain-id "Binance-Chain-Tigris" --node tcp://dataseed4.binance.org:80`

I get this result:

```
I[2020-02-24|15:05:08.985] Connecting to source HTTP client...          
I[2020-02-24|15:05:08.986] Constructing Verifier...                     
I[2020-02-24|15:05:08.986] lite/proxy/NewVerifier()...                  module=lite/proxy chainID=Binance-Chain-Tigris rootDir=.binance-lite client=WSEvents
I[2020-02-24|15:05:09.114] DBProvider.LatestFullCommit()...             module=lite label=trusted.mem chainID=Binance-Chain-Tigris minHeight=1 maxHeight=9223372036854775807
I[2020-02-24|15:05:09.114] DBProvider.LatestFullCommit()...             module=lite label=trusted.lvl chainID=Binance-Chain-Tigris minHeight=1 maxHeight=9223372036854775807
I[2020-02-24|15:05:09.115] lite/proxy/NewVerifier found no trusted full commit, initializing from source from height 1... module=lite/proxy 
Error: Status: error unmarshalling rpc response: invalid character '<' looking for beginning of value
panic: Status: error unmarshalling rpc response: invalid character '<' looking for beginning of value

goroutine 1 [running]:
main.main()
	/home/suyu/go/src/github.com/binance-chain/node/cmd/lightd/main.go:22 +0x5b
```

**Comment by huangsuyu** [comment]
hello, which version of `lightd` doid you use?

Can you follow the [script](https://github.com/binance-chain/node-binary/blob/master/install.sh) and get the latest version. 

This is what i got:
```
lightd --chain-id "Binance-Chain-Tigris" --node tcp://dataseed2.ninicoin.io:80
I[2020-02-25|10:22:42.479] Connecting to source HTTP client...
I[2020-02-25|10:22:42.479] Constructing Verifier...
I[2020-02-25|10:22:42.479] lite/proxy/NewVerifier()...                  module=lite/proxy chainID=Binance-Chain-Tigris rootDir=.binance-lite client=WSEvents
I[2020-02-25|10:22:42.502] DBProvider.LatestFullCommit()...             module=lite label=trusted.mem chainID=Binance-Chain-Tigris minHeight=1 maxHeight=9223372036854775807
I[2020-02-25|10:22:42.502] DBProvider.LatestFullCommit()...             module=lite label=trusted.lvl chainID=Binance-Chain-Tigris minHeight=1 maxHeight=9223372036854775807
I[2020-02-25|10:22:42.502] lite/proxy/NewVerifier found no trusted full commit, initializing from source from height 1... module=lite/proxy
I[2020-02-25|10:22:44.378] DBProvider.SaveFullCommit()...               module=lite label=trusted.mem fc="{SignedHeader:SignedHeader{\n  Header{\n    Version:        {10 0}\n    ChainID:        Binance-Chain-Tigris\n    Height:         1\n    Time:           2019-04-18 05:59:26.228734998 +0000 UTC\n    NumTxs:         0\n    TotalTxs:       0\n    LastBlockID:    :0:000000000000\n    LastCommit:     \n    Data:           \n    Validators:     43C53A50D8653EF8CF1E5716DA68120FB51B636DC6D111EC3277B098ECD42D49\n    NextValidators: 43C53A50D8653EF8CF1E5716DA68120FB51B636DC6D111EC3277B098ECD42D49\n    App:            \n    Consensus:       294D8FBD0B94B767A7EBA9840F299A3586DA7FE6B5DEAD3B7EECBA193C400F93\n    Results:        \n    Evidence:       \n    Proposer:       14CFCE69B645F3F88BAF08EA5B77FA521E4480F9\n  }#494A674FCDADB0F67BC99CBC33B6F8061E1B76A786485B662EE422C6918C86C8\n  Commit{\n    BlockID:    494A674FCDADB0F67BC99CBC33B6F8061E1B76A786485B662EE422C6918C86C8:1:AF4CEDFAB7FB\n    Precommits:\n      nil-Vote\n      Vote{1:14CFCE69B645 1/01/2(Precommit) 494A674FCDAD 8DBB876827D3 @ 2019-04-18T06:07:02.233083179Z}\n      Vote{2:17B42E8F284D 1/01/2(Precommit) 494A674FCDAD C38376153D5F @ 2019-04-18T06:07:02.153180042Z}\n      Vote{3:3CD4AABABDDE 1/01/2(Precommit) 494A674FCDAD 9B366E30633F @ 2019-04-18T06:07:02.23279118Z}\n      Vote{4:414FB3BBA216 1/01/2(Precommit) 494A674FCDAD 2444EC707AE8 @ 2019-04-18T06:07:02.154340159Z}\n      Vote{5:71F253E6FEA9 1/01/2(Precommit) 494A674FCDAD 9FCA0F35360B @ 2019-04-18T06:07:02.23639005Z}\n      nil-Vote\n      Vote{7:A71E5CD078B8 1/01/2(Precommit) 494A674FCDAD D27BA17D45DC @ 2019-04-18T06:07:02.232155249Z}\n      Vote{8:A9157B3FA6EB 1/01/2(Precommit) 494A674FCDAD ABF630D326AC @ 2019-04-18T06:07:02.153428422Z}\n      Vote{9:B0FBB52FF7EE 1/01/2(Precommit) 494A674FCDAD 4D5D95CC2AB1 @ 2019-04-18T06:07:02.153867648Z}\n      nil-Vote\n  }#\n} Validators:ValidatorSet{\n  Proposer: Validator{1175946A48EAA473868A0A6F52E6C66CCAF472EA PubKeyEd25519{D3769D8A1F78B4C17A965F7A30D4181FABBD1F969F46D3C8E83B5AD4845421D8} VP:1000000000000 A:-10000000000000}\n  Validators:\n    Validator{1175946A48EAA473868A0A6F52E6C66CCAF472EA PubKeyEd25519{D3769D8A1F78B4C17A965F7A30D4181FABBD1F969F46D3C8E83B5AD4845421D8} VP:1000000000000 A:-10000000000000}\n    Validator{14CFCE69B645F3F88BAF08EA5B77FA521E4480F9 PubKeyEd25519{2BA4E81542F437B7AE1F8A35DDB233C789A8DC22734377D9B6D63AF1CA403B61} VP:1000000000000 A:1000000000000}\n    Validator{17B42E8F284D3CA0E420262F89CD76C749BB12C9 PubKeyEd25519{DF8DA8C5ABFDB38595391308BB71E5A1E0AABDC1D0CF38315D50D6BE939B2606} VP:1000000000000 A:1000000000000}\n    Validator{3CD4AABABDDEB7ABFEA9618732E331077A861D2B PubKeyEd25519{B6619EDCA4143484800281D698B70C935E9152AD57B31D85C05F2F79F64B39F3} VP:1000000000000 A:1000000000000}\n    Validator{414FB3BBA216AF84C47E07D6EBAA2DCFC3563A2F PubKeyEd25519{9446D14AD86C8D2D74780B0847110001A1C2E252EEDFEA4753EBBBFCE3A22F52} VP:1000000000000 A:1000000000000}\n    Validator{71F253E6FEA9EDD4B4753F5483549FE4F0F3A21C PubKeyEd25519{0353C639F80CC8015944436DAB1032245D44F912EDC31EF668FF9F4A45CD0599} VP:1000000000000 A:1000000000000}\n    Validator{7235EF143D20FC0ABC427615D83014BB02D7C06C PubKeyEd25519{E81D3797E0544C3A718E1F05F0FB782212E248E784C1A851BE87E77AE0DB230E} VP:1000000000000 A:1000000000000}\n    Validator{A71E5CD078B8C5C7B1AF88BCE84DD70B0557D93E PubKeyEd25519{5E3FCDA30BD19D45C4B73688DA35E7DA1FCE7C6859B2C1F20ED5202D24144E3E} VP:1000000000000 A:1000000000000}\n    Validator{A9157B3FA6EB4C1E396B9B746E95327A07DC42E5 PubKeyEd25519{B06A59A2D75BF5D014FCE7C999B5E71E7A960870F725847D4BA3235BAEAA08EF} VP:1000000000000 A:1000000000000}\n    Validator{B0FBB52FF7EE93CC476DFE6B74FA1FC88584F30D PubKeyEd25519{0C910E2FE650E4E01406B3310B489FB60A84BC3FF5C5BEE3A56D5898B6A8AF32} VP:1000000000000 A:1000000000000}\n    Validator{B7707D9F593C62E85BB9E1A2366D12A97CD5DFF2 PubKeyEd25519{71F2D7B8EC1C8B99A653429B0118CD201F794F409D0FEA4D65B1B662F2B00063} VP:1000000000000 A:1000000000000}\n} NextValidators:ValidatorSet{\n  Proposer: Validator{1175946A48EAA473868A0A6F52E6C66CCAF472EA PubKeyEd25519{D3769D8A1F78B4C17A965F7A30D4181FABBD1F969F46D3C8E83B5AD4845421D8} VP:1000000000000 A:-10000000000000}\n  Validators:\n    Validator{1175946A48EAA473868A0A6F52E6C66CCAF472EA PubKeyEd25519{D3769D8A1F78B4C17A965F7A30D4181FABBD1F969F46D3C8E83B5AD4845421D8} VP:1000000000000 A:-10000000000000}\n    Validator{14CFCE69B645F3F88BAF08EA5B77FA521E4480F9 PubKeyEd25519{2BA4E81542F437B7AE1F8A35DDB233C789A8DC22734377D9B6D63AF1CA403B61} VP:1000000000000 A:1000000000000}\n    Validator{17B42E8F284D3CA0E420262F89CD76C749BB12C9 PubKeyEd25519{DF8DA8C5ABFDB38595391308BB71E5A1E0AABDC1D0CF38315D50D6BE939B2606} VP:1000000000000 A:1000000000000}\n    Validator{3CD4AABABDDEB7ABFEA9618732E331077A861D2B PubKeyEd25519{B6619EDCA4143484800281D698B70C935E9152AD57B31D85C05F2F79F64B39F3} VP:1000000000000 A:1000000000000}\n    Validator{414FB3BBA216AF84C47E07D6EBAA2DCFC3563A2F PubKeyEd25519{9446D14AD86C8D2D74780B0847110001A1C2E252EEDFEA4753EBBBFCE3A22F52} VP:1000000000000 A:1000000000000}\n    Validator{71F253E6FEA9EDD4B4753F5483549FE4F0F3A21C PubKeyEd25519{0353C639F80CC8015944436DAB1032245D44F912EDC31EF668FF9F4A45CD0599} VP:1000000000000 A:1000000000000}\n    Validator{7235EF143D20FC0ABC427615D83014BB02D7C06C PubKeyEd25519{E81D3797E0544C3A718E1F05F0FB782212E248E784C1A851BE87E77AE0DB230E} VP:1000000000000 A:1000000000000}\n    Validator{A71E5CD078B8C5C7B1AF88BCE84DD70B0557D93E PubKeyEd25519{5E3FCDA30BD19D45C4B73688DA35E7DA1FCE7C6859B2C1F20ED5202D24144E3E} VP:1000000000000 A:1000000000000}\n    Validator{A9157B3FA6EB4C1E396B9B746E95327A07DC42E5 PubKeyEd25519{B06A59A2D75BF5D014FCE7C999B5E71E7A960870F725847D4BA3235BAEAA08EF} VP:1000000000000 A:1000000000000}\n    Validator{B0FBB52FF7EE93CC476DFE6B74FA1FC88584F30D PubKeyEd25519{0C910E2FE650E4E01406B3310B489FB60A84BC3FF5C5BEE3A56D5898B6A8AF32} VP:1000000000000 A:1000000000000}\n    Validator{B7707D9F593C62E85BB9E1A2366D12A97CD5DFF2 PubKeyEd25519{71F2D7B8EC1C8B99A653429B0118CD201F794F409D0FEA4D65B1B662F2B00063} VP:1000000000000 A:1000000000000}\n}}"
```

**Comment by xana-rahmani** [comment]
Thank you. 
The problem was the nodes. 
Now the my script worked correctly and node are executed.

**Comment by huangsuyu** [comment]
Cool, I close this issue for now. Please reopen when necessary.

**Comment by DannyDevil0** [comment]
Hi,
My script gives the same error 
invalid character '<' looking for beginning of value
When fetching transactions from blocks.

Doesn't happen with all blocks but some.
