### ISSUE TITLE
panic: Failed to process committed block (99550001)

### ISSUE THREAD

**Issue by Alteryy** [binance-chain/node-binary#221]
panic: Failed to process committed block (99550001:591E99E27F36C4BDB939F1D35E1F3D1F51BA0CE5F82624024470233F5568B055): Wrong Block.Header.AppHash.  Expected 16420A2203305D86BB6AAE985CD8E66FFF28E16D047FD5E0FE18A9054172A1B4, got F269C5089D10AC2D6AAC6CE27AF34B95166B4EEC24AE1705D838F9265D0531A5

goroutine 47089 [running]:
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc000f0c820)
        /Users/huangsuyu/go/pkg/mod/github.com/binance-chain/bnc-tendermint@v0.32.3-binance.1/blockchain/v0/reactor.go:399 +0x18cc
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
        /Users/huangsuyu/go/pkg/mod/github.com/binance-chain/bnc-tendermint@v0.32.3-binance.1/blockchain/v0/reactor.go:126 +0x84

:~# ./bnbchaind version
Binance Chain Release: 0.7.2;Binance Chain Commit: 56c4912a; Cosmos Release: v0.25.0-binance.22; Tendermint Release: v0.32.3-binance.1;

**Comment by Alteryy** [comment]
app.toml

add config,
# Block height of BEP8 upgrade
BEP8Height = 99550000
# Block height of BEP67 upgrade
BEP67Height = 99550000
# Block height of BEP70 upgrade
BEP70Height = 99550000
