### ISSUE TITLE
API is not serving requests

### ISSUE THREAD

**Issue by ArseniiPetrovich** [binance-chain/node-binary#238]
Hi, team. Recently we upgraded our node to 0.7.2 and faced the following issue with the API server:
```
Aug 24 09:35:33 ip-172-31-29-224 bnbcli: E[2020-08-24|09:35:33.664] Panic in RPC HTTP handler                    module=apiserv err="Unmarshal expects a pointer" stack="goroutine 834189 [running]:\nruntime/debug.Stack(0xc000a57198, 0x10841c0, 0x155c2c0)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9d\ngithub.com/tendermint/tendermint/rpc/lib/server.RecoverAndLogHandler.func1.1(0xc000350ce0, 0x159c660, 0xc0000cda80, 0xbfc900596764c450, 0x17c34595f3ff1, 0x1f20fc0, 0xc000a35a00)\n\t/Users/huangsuyu/go/pkg/mod/github.com/binance-chain/bnc-tendermint@v0.32.3-binance.1/rpc/lib/server/http_server.go:161 +0x486\npanic(0x10841c0, 0x155c2c0)\n\t/usr/local/go/src/runtime/panic.go:679 +0x1b2\ngithub.com/tendermint/go-amino.(*Codec).UnmarshalBinaryBare(0xc0000fc460, 0xc00017c0f1, 0x41, 0x41, 0x0, 0x0, 0x0, 0x0)\n\t/Users/huangsuyu/go/pkg/mod/github.com/binance-chain/bnc-go-amino@v0.14.1-binance.2/amino.go:325 +0x871\ngithub.com/tendermint/go-amino.(*Codec).UnmarshalBinaryLengthPrefixed(0xc0000fc460, 0xc00017c0f0, 0x41, 0x42, 0x0, 0x0, 0x0, 0x7ffdc0b72f05)\n\t/Users/huangsuyu/go/pkg/mod/github.com/binance-chain/bnc-go-amino@v0.14.1-binance.2/amino.go:253 +0xf3\ngithub.com/binance-chain/node/plugins/tokens/client/rest.getTokenInfo(0xc0000fc460, 0xc000a0abd0, 0x15ba380, 0xc0009bb470, 0x157ae20, 0xc0000b2008, 0x0, 0x7ffdc0b72f05, 0x15, 0x0, ...)\n\t/Users/huangsuyu/go/src/github.com/binance-chain/node/plugins/tokens/client/rest/gettoken.go:30 +0x1f4\ngithub.com/binance-chain/node/plugins/tokens/client/rest.GetTokenReqHandler.func2(0x1595e60, 0xc000350ce0, 0xc000a35c00)\n\t/Users/huangsuyu/go/src/github.com/binance-chain/node/plugins/tokens/client/rest/gettoken.go:69 +0x219\nnet/http.HandlerFunc.ServeHTTP(0xc000a96200, 0x1595e60, 0xc000350ce0, 0xc000a35c00)\n\t/usr/local/go/src/net/http/server.go:2007 +0x44\ngithub.com/gorilla/mux.(*Router).ServeHTTP(0xc00033ecc0, 0x1595e60, 0xc000350ce0, 0xc000a35a00)\n\t/Users/huangsuyu/go/pkg/mod/github.com/gorilla/mux@v1.7.3/mux.go:212 +0xe2\ngithub.com/tendermint/tendermint/rpc/lib/server.maxBytesHandler.ServeHTTP(0x1579940, 0xc00033ecc0, 0x0, 0x1595e60, 0xc000350ce0, 0xc000a35a00)\n\t/Users/huangsuyu/go/pkg/mod/github.com/binance-chain/bnc-tendermint@v0.32.3-binance.1/rpc/lib/server/http_server.go:206 +0xcf\ngithub.com/tendermint/tendermint/rpc/lib/server.RecoverAndLogHandler.func1(0x1596660, 0xc000a121c0, 0xc000a35a00)\n\t/Users/huangsuyu/go/pkg/mod/github.com/binance-chain/bnc-tendermint@v0.32.3-binance.1/rpc/lib/server/http_server.go:179 +0x33f\nnet/http.HandlerFunc.ServeHTTP(0xc000bbd2c0, 0x1596660, 0xc000a121c0, 0xc000a35a00)\n\t/usr/local/go/src/net/http/server.go:2007 +0x44\nnet/http.serverHandler.ServeHTTP(0xc0010ec000, 0x1596660, 0xc000a121c0, 0xc000a35a00)\n\t/usr/local/go/src/net/http/server.go:2802 +0xa4\nnet/http.(*conn).serve(0xc000b66460, 0x159b220, 0xc000a968c0)\n\t/usr/local/go/src/net/http/server.go:1890 +0x875\ncreated by net/http.(*Server).Serve\n\t/usr/local/go/src/net/http/server.go:2927 +0x38e\n"
Aug 24 09:35:33 ip-172-31-29-224 bnbcli: 2020/08/24 09:35:33 http: panic serving 10.10.2.76:45540: interface conversion: string is not error: missing method Error

```
Could you help us solving it? It is kinda critical for our application.
Thanks!

**Comment by huangsuyu** [comment]
May I ask if the fullnode you connect with is synced?

**Comment by ArseniiPetrovich** [comment]
```
    "sync_info": {
      "latest_block_hash": "E88E653042ECAE237F6B820018F2DD147C3E73C209484BC3D5E1A558C94FA4C9",
      "latest_app_hash": "E55B7AFB7C9AA7B37CB9FA2EFB75F8B20B8F8314D61E85DD676B22877B6651D0",
      "latest_block_height": "109216137",
      "latest_block_time": "2020-08-24T10:33:24.949411948Z",
      "catching_up": true,
      "index_height": "0"
    },
```
Well, it seems that it is still catching up. Might that affect?

I'm querying the following endpoint: `/api/v1/tokens/TUSDB-888`

**Comment by huangsuyu** [comment]
@ArseniiPetrovich   Could you switch to https://dex.binance.org/api/v1/tokens?limit=500 for a while?

**Comment by ArseniiPetrovich** [comment]
> @ArseniiPetrovich Could you switch to https://dex.binance.org/api/v1/tokens?limit=500 for a while?

Well, the idea of our app is to provide a Secure information from trusted endpoint we host, but if you are looking for some debug info we can switch our dev env to this endpoint.

**Comment by ArseniiPetrovich** [comment]
We use in our app
`/timelock/timelocks/${address}`
and
`/balances/${address}/${symbol}`
and it doesn’t work too
`/balances/bnb100dxzy02a6k7vysc5g4kk4fqamr7jhjg4m83l0/TUSDB-888 GET 404:Not Found {“message”:“no route and no API found with those values”}`

The URL you provided us with works well.

**Comment by ArseniiPetrovich** [comment]
So we just downgraded API server to 0.6.8 and it works fine :D

**Comment by ArseniiPetrovich** [comment]
```
● binance-api.service - BNB chain fullnode API server
   Loaded: loaded (/etc/systemd/system/binance-api.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2020-08-26 12:51:14 UTC; 4min 52s ago
 Main PID: 8567 (bnbcli)
   CGroup: /system.slice/binance-api.service
           └─8567 /home/ec2-user/node-binary/cli/prod/0.8.0/linux/bnbcli api-server --chain-id Binance-Chain-Tigris --trust-node --node tcp://localhost:27147 --laddr tcp://0.0.0.0:8080

Aug 26 12:56:02 ip-172-31-29-224.us-east-2.compute.internal bnbcli[8567]: github.com/tendermint/tendermint/rpc/lib/server.RecoverAndLogHandler.func1(0x16dbee0, 0xc0000e8700, 0xc000c8b700)
Aug 26 12:56:02 ip-172-31-29-224.us-east-2.compute.internal bnbcli[8567]: /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-tendermint@v0.32.3-binance.3/rpc/lib/server/http_server.go:179 +0x317
Aug 26 12:56:02 ip-172-31-29-224.us-east-2.compute.internal bnbcli[8567]: net/http.HandlerFunc.ServeHTTP(0xc000d7a540, 0x16dbee0, 0xc0000e8700, 0xc000c8b700)
Aug 26 12:56:02 ip-172-31-29-224.us-east-2.compute.internal bnbcli[8567]: /opt/go/src/net/http/server.go:1995 +0x44
Aug 26 12:56:02 ip-172-31-29-224.us-east-2.compute.internal bnbcli[8567]: net/http.serverHandler.ServeHTTP(0xc000aa5380, 0x16dbee0, 0xc0000e8700, 0xc000c8b700)
Aug 26 12:56:02 ip-172-31-29-224.us-east-2.compute.internal bnbcli[8567]: /opt/go/src/net/http/server.go:2774 +0xa8
Aug 26 12:56:02 ip-172-31-29-224.us-east-2.compute.internal bnbcli[8567]: net/http.(*conn).serve(0xc000db0be0, 0x16e16e0, 0xc000e96940)
Aug 26 12:56:02 ip-172-31-29-224.us-east-2.compute.internal bnbcli[8567]: /opt/go/src/net/http/server.go:1878 +0x851
Aug 26 12:56:02 ip-172-31-29-224.us-east-2.compute.internal bnbcli[8567]: created by net/http.(*Server).Serve
Aug 26 12:56:02 ip-172-31-29-224.us-east-2.compute.internal bnbcli[8567]: /opt/go/src/net/http/server.go:2884 +0x2f4
```
I'm sorry, seems 0.8.0 does not fix this. Or maybe I'm doing something wrong :(

**Comment by huangsuyu** [comment]
@ArseniiPetrovich  I am closing this, please report when necessary.
