### ISSUE TITLE
"panic: Cannot find any publisher in config, there might be some wrong configuration" error when starting bnbchaind

### ISSUE THREAD

**Issue by mahsumurebe** [binance-chain/node-binary#241]
Since the Chain #204 issue keeps repeating the error, I deleted all the blockchain data and installed it with snapshot. But when I run bnbchaind it throws the following error.

```
panic: Cannot find any publisher in config, there might be some wrong configuration

goroutine 1 [running]:
github.com/binance-chain/node/app.NewBinanceChain(0x1aa8b80, 0xc000e452c0, 0x1ac33a0, 0xc0000be180, 0x0, 0x0, 0x0, 0x0, 0x0, 0x100)
        /root/bnbchain/src/github.com/binance-chain/node/app/app.go:213 +0x3bdd
main.newApp(0x1aa8b80, 0xc000e452c0, 0x1ac33a0, 0xc0000be180, 0x0, 0x0, 0xc0009fa000, 0xc000f29920)
        /root/bnbchain/src/github.com/binance-chain/node/cmd/bnbchaind/main.go:23 +0x78
github.com/cosmos/cosmos-sdk/server.startInProcess(0xc000dc14a0, 0x18439e8, 0x1d, 0x0, 0x0)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-cosmos-sdk@v0.25.0-binance.23/server/start.go:117 +0x187
github.com/cosmos/cosmos-sdk/server.StartCmd.func1(0xc000dee780, 0xc000de2d20, 0x0, 0x1, 0x0, 0x0)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-cosmos-sdk@v0.25.0-binance.23/server/start.go:44 +0xb5
github.com/spf13/cobra.(*Command).execute(0xc000dee780, 0xc000de2d00, 0x1, 0x1, 0xc000dee780, 0xc000de2d00)
        /root/bnbchain/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x465
github.com/spf13/cobra.(*Command).ExecuteC(0xc000dd6c80, 0x2, 0xc000dc1740, 0x16cd647)
        /root/bnbchain/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
        /root/bnbchain/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc000dd6c80, 0x1843e00, 0x2, 0xc000d31c70)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-tendermint@v0.32.3-binance.3/libs/cli/setup.go:89 +0x3c
main.main()
        /root/bnbchain/src/github.com/binance-chain/node/cmd/bnbchaind/main.go:54 +0x3ef
```

I downloaded the July snapshot at https://docs.binance.org/guides/node/snapshot.html and extracted it to `/data/resources`. Only data folder was extracted from Snapshot. The bnc.log.* files were not created. Is there a problem here? If the bnc.log.* files do not contain blockchain information, I want to delete them regularly. They use a lot of disk space.

*PS:* I changed the home folder path. New home path set to `/data/resources`. I changed the config folder in the main folder with the symbolic link to the `/data/config` location.

**Comment by mahsumurebe** [comment]
Any ideas?

**Comment by aghamir** [comment]
Did you find a solution? I get this error too.

**Comment by mahsumurebe** [comment]
The problem with the error message was that I didn't update the config. It is necessary to update the repository with new configs.
