### ISSUE TITLE
too many open files

### ISSUE THREAD

**Issue by mahsumurebe** [binance-chain/node-binary#251]
"Too many open files" error occurs while the node is running. [bnbchaind crashes because of too many open files
](https://docs.binance.org/fullnodeissue.html#bnbchaind-crashes-because-of-too-many-open-files) applied the solution here. But there was no solution.

`System:`
```
CPU: 4 Core
RAM: 8GB
Disc: 1.5 TB
```

`df -h output:`
```
Filesystem      Size  Used Avail Use% Mounted on
udev            3.9G     0  3.9G   0% /dev
tmpfs           798M   12M  787M   2% /run
/dev/vda1       1.4T  849G  516G  63% /
tmpfs           3.9G     0  3.9G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
tmpfs           798M     0  798M   0% /run/user/0

```

*bnbchain version output:*
`Binance Chain Release: v0.8.0;Binance Chain Commit: 422f0a96; Cosmos Release: v0.25.0-binance.23; Tendermint Release: v0.32.3-binance.3;`

*ulimit -a output:*
```
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 31662
max locked memory       (kbytes, -l) 16384
max memory size         (kbytes, -m) unlimited
open files                      (-n) 999999
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 31662
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

*Error Log:*
```
panic: open /data/resources/data/application.db/136155467.ldb: too many open files
goroutine 469413 [running]:
github.com/tendermint/tendermint/libs/db.(*GoLevelDB).Get(0xc000010058, 0xc02225d230, 0x29, 0x29, 0xc03a8c37e5, 0xc006ca52c0, 0xc02225d200)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-tendermint@v0.32.3-binance.3/libs/db/go_level_db.go:56 +0x137
github.com/tendermint/tendermint/libs/db.(*prefixDB).Get(0xc000d5b560, 0xc02225d200, 0x21, 0x21, 0x0, 0x0, 0x0)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-tendermint@v0.32.3-binance.3/libs/db/prefix_db.go:60 +0x14a
github.com/tendermint/iavl.(*nodeDB).GetNode(0xc000d5b9b0, 0xc025175760, 0x20, 0x20, 0x0)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-tendermint-iavl@v0.12.0-binance.4/nodedb.go:66 +0x133
github.com/tendermint/iavl.(*Node).getRightNode(0xc03bc8f500, 0xc023b9b840, 0x0, 0x0)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-tendermint-iavl@v0.12.0-binance.4/node.go:413 +0x195
github.com/tendermint/iavl.(*Node).get(0xc03bc8f500, 0xc023b9b840, 0xc025b4d440, 0x1c, 0x20, 0x1c, 0xffffffffffffffff, 0xc035ba2060, 0x1844370)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-tendermint-iavl@v0.12.0-binance.4/node.go:190 +0x218
github.com/tendermint/iavl.(*Node).get(0xc03bc8f440, 0xc023b9b840, 0xc025b4d440, 0x1c, 0x20, 0x1c, 0xffffffffffffffff, 0xc035ba2060, 0x1844370)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-tendermint-iavl@v0.12.0-binance.4/node.go:188 +0x1bd
github.com/tendermint/iavl.(*Node).get(0xc03bc8f380, 0xc023b9b840, 0xc025b4d440, 0x1c, 0x20, 0x1c, 0xffffffffffffffff, 0xc035ba2060, 0x1844370)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-tendermint-iavl@v0.12.0-binance.4/node.go:188 +0x1bd
github.com/tendermint/iavl.(*Node).get(0xc03bc8f2c0, 0xc023b9b840, 0xc025b4d440, 0x1c, 0x20, 0x1c, 0x1, 0xc035ba2060, 0x1844370)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-tendermint-iavl@v0.12.0-binance.4/node.go:188 +0x1bd
github.com/tendermint/iavl.(*Node).get(0xc03bc8f200, 0xc023b9b840, 0xc025b4d440, 0x1c, 0x20, 0x1c, 0x1, 0xc035ba2060, 0x1844370)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-tendermint-iavl@v0.12.0-binance.4/node.go:191 +0x256
github.com/tendermint/iavl.(*Node).get(0xc03bc8f140, 0xc023b9b840, 0xc025b4d440, 0x1c, 0x20, 0x1c, 0xffffffffffffffff, 0xc035ba2060, 0x1844370)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-tendermint-iavl@v0.12.0-binance.4/node.go:191 +0x256
github.com/tendermint/iavl.(*Node).get(0xc03bc8f080, 0xc023b9b840, 0xc025b4d440, 0x1c, 0x20, 0x1c, 0xffffffffffffffff, 0xc035ba2060, 0x1844370)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-tendermint-iavl@v0.12.0-binance.4/node.go:188 +0x1bd
github.com/tendermint/iavl.(*Node).get(0xc03bc8efc0, 0xc023b9b840, 0xc025b4d440, 0x1c, 0x20, 0x1c, 0xffffffffffffffff, 0xc035ba2060, 0x1844370)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-tendermint-iavl@v0.12.0-binance.4/node.go:188 +0x1bd
github.com/tendermint/iavl.(*Node).get(0xc03bc8ef00, 0xc023b9b840, 0xc025b4d440, 0x1c, 0x20, 0x1c, 0xffffffffffffffff, 0xc035ba2060, 0x1844370)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-tendermint-iavl@v0.12.0-binance.4/node.go:188 +0x1bd
github.com/tendermint/iavl.(*Node).get(0xc03bc8ee40, 0xc023b9b840, 0xc025b4d440, 0x1c, 0x20, 0x1c, 0x1, 0x148c5c0, 0x0)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-tendermint-iavl@v0.12.0-binance.4/node.go:188 +0x1bd
github.com/tendermint/iavl.(*Node).get(0xc03bc8ed80, 0xc023b9b840, 0xc025b4d440, 0x1c, 0x20, 0x1c, 0xffffffffffffffff, 0x142e2c0, 0x10)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-tendermint-iavl@v0.12.0-binance.4/node.go:191 +0x256
github.com/tendermint/iavl.(*Node).get(0xc02a90d500, 0xc023b9b840, 0xc025b4d440, 0x1c, 0x20, 0x1c, 0x1, 0x10, 0xc006ca5850)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-tendermint-iavl@v0.12.0-binance.4/node.go:188 +0x1bd
github.com/tendermint/iavl.(*Node).get(0xc02a90ce40, 0xc023b9b840, 0xc025b4d440, 0x1c, 0x20, 0x1c, 0x1, 0x14ccc20, 0x12)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-tendermint-iavl@v0.12.0-binance.4/node.go:191 +0x256
github.com/tendermint/iavl.(*Node).get(0xc03238f8c0, 0xc023b9b840, 0xc025b4d440, 0x1c, 0x20, 0x1c, 0x1, 0x6213, 0x1ad3460)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-tendermint-iavl@v0.12.0-binance.4/node.go:191 +0x256
github.com/tendermint/iavl.(*Node).get(0xc03238f5c0, 0xc023b9b840, 0xc025b4d440, 0x1c, 0x20, 0x1c, 0xffffffffffffffff, 0xe, 0x0)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-tendermint-iavl@v0.12.0-binance.4/node.go:191 +0x256
github.com/tendermint/iavl.(*Node).get(0xc0270a9080, 0xc023b9b840, 0xc025b4d440, 0x1c, 0x20, 0x1c, 0xffffffffffffffff, 0x142e2c0, 0x145baa0)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-tendermint-iavl@v0.12.0-binance.4/node.go:188 +0x1bd
github.com/tendermint/iavl.(*Node).get(0xc0266f5b00, 0xc023b9b840, 0xc025b4d440, 0x1c, 0x20, 0x1c, 0xffffffffffffffff, 0xc006ca5a40, 0x411496)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-tendermint-iavl@v0.12.0-binance.4/node.go:188 +0x1bd
github.com/tendermint/iavl.(*Node).get(0xc0266f55c0, 0xc023b9b840, 0xc025b4d440, 0x1c, 0x20, 0x1c, 0x1, 0x73e46ab0, 0xa25652f833e647f8)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-tendermint-iavl@v0.12.0-binance.4/node.go:188 +0x1bd
github.com/tendermint/iavl.(*Node).get(0xc021739080, 0xc023b9b840, 0xc025b4d440, 0x1c, 0x20, 0x1c, 0x1, 0x20, 0xc025b4d440)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-tendermint-iavl@v0.12.0-binance.4/node.go:191 +0x256
github.com/tendermint/iavl.(*Node).get(0xc0000d0a80, 0xc023b9b840, 0xc025b4d440, 0x1c, 0x20, 0x418c00, 0xc006ca5b78, 0x453832, 0xc025b4d440)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-tendermint-iavl@v0.12.0-binance.4/node.go:191 +0x256
github.com/tendermint/iavl.(*ImmutableTree).Get(0xc023b9b840, 0xc025b4d440, 0x1c, 0x20, 0x20, 0x1448900, 0xc025b4d440, 0xc025b4d440)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-tendermint-iavl@v0.12.0-binance.4/immutable_tree.go:155 +0x6a
github.com/cosmos/cosmos-sdk/store.(*IavlStore).Get(0xc003d446c0, 0xc025b4d440, 0x1c, 0x20, 0x1c, 0xc025b4d440, 0x8)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-cosmos-sdk@v0.25.0-binance.23/store/iavlstore.go:153 +0x4f
github.com/cosmos/cosmos-sdk/x/auth.(*accountStoreCache).GetAccount(0xc013d25300, 0xc027379ee0, 0x14, 0x14, 0x0, 0x0)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-cosmos-sdk@v0.25.0-binance.23/x/auth/mapper.go:236 +0x13d
github.com/cosmos/cosmos-sdk/x/auth.(*accountCache).getAccountFromCache(0xc017d83fc0, 0xc027379ee0, 0x14, 0x14, 0x0, 0x102ca5c96)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-cosmos-sdk@v0.25.0-binance.23/x/auth/mapper.go:359 +0x14d
github.com/cosmos/cosmos-sdk/x/auth.(*accountCache).GetAccount(0xc017d83fc0, 0xc027379ee0, 0x14, 0x14, 0x1e, 0x3)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-cosmos-sdk@v0.25.0-binance.23/x/auth/mapper.go:299 +0x49
github.com/cosmos/cosmos-sdk/x/auth.AccountKeeper.GetAccount(0x1a931c0, 0xc00047c020, 0x1840be8, 0xc000d92230, 0x1aa7740, 0xc000046018, 0x1ac0220, 0xc0129a8380, 0xa, 0x0, ...)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-cosmos-sdk@v0.25.0-binance.23/x/auth/mapper.go:87 +0x94
github.com/cosmos/cosmos-sdk/x/bank.getCoins(0x1aa7740, 0xc000046018, 0x1ac0220, 0xc0129a8380, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-cosmos-sdk@v0.25.0-binance.23/x/bank/keeper.go:164 +0xba
github.com/cosmos/cosmos-sdk/x/bank.addCoins(0x1aa7740, 0xc000046018, 0x1ac0220, 0xc0129a8380, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-cosmos-sdk@v0.25.0-binance.23/x/bank/keeper.go:204 +0xc5
github.com/cosmos/cosmos-sdk/x/bank.BaseKeeper.AddCoins(...)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-cosmos-sdk@v0.25.0-binance.23/x/bank/keeper.go:65
github.com/cosmos/cosmos-sdk/x/stake/keeper.Keeper.Distribute(0x1a931c0, 0xc00047c070, 0x1a93200, 0xc00047c140, 0xc000d92230, 0x1aba9c0, 0xc00000fbc0, 0xc0008da320, 0x1ac14a0, 0xc034ff99a0, ...)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-cosmos-sdk@v0.25.0-binance.23/x/stake/keeper/distribute_sidechain.go:42 +0xff9
github.com/cosmos/cosmos-sdk/x/stake.EndBreatheBlock(0x1aa7740, 0xc000046018, 0x1ac0220, 0xc0129a8380, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-cosmos-sdk@v0.25.0-binance.23/x/stake/endblock.go:38 +0x60f
github.com/binance-chain/node/app.(*BinanceChain).EndBlocker(0xc0000d4900, 0x1aa7740, 0xc000046018, 0x1ac0220, 0xc0129a8380, 0xa, 0x0, 0x0, 0x0, 0x0, ...)
        /root/bnbchain/src/github.com/binance-chain/node/app/app.go:817 +0xcc0
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).EndBlock(0xc0009051d0, 0x6b5bb6d, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-cosmos-sdk@v0.25.0-binance.23/baseapp/baseapp.go:936 +0x12a
github.com/cosmos/cosmos-sdk/server/concurrent.(*asyncLocalClient).EndBlockSync(0xc000db0210, 0x6b5bb6d, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-cosmos-sdk@v0.25.0-binance.23/server/concurrent/async_local_client.go:408 +0x201
github.com/tendermint/tendermint/proxy.(*appConnConsensus).EndBlockSync(0xc0147edce0, 0x6b5bb6d, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-tendermint@v0.32.3-binance.3/proxy/app_conn.go:115 +0x51
github.com/tendermint/tendermint/state.execBlockOnProxyApp(0x1aa8b80, 0xc017d24b80, 0x1ab7420, 0xc0147edce0, 0xc03c396f00, 0xc006cad960, 0x1ac33a0, 0xc02e3060d8, 0xc03d8482c0, 0x14, ...)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-tendermint@v0.32.3-binance.3/state/execution.go:298 +0x702
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(0xc0231622a0, 0xa, 0x0, 0xc02dce8a80, 0x6, 0xc03d8482c0, 0x14, 0x6b5bb6c, 0x7904c89, 0xc029f13fa0, ...)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-tendermint@v0.32.3-binance.3/state/execution.go:128 +0x1c2
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc00002f520)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-tendermint@v0.32.3-binance.3/blockchain/v0/reactor.go:401 +0xa57
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-tendermint@v0.32.3-binance.3/blockchain/v0/reactor.go:127 +0x84
```

**Comment by mahsumurebe** [comment]
Anyone have any idea about the problem?

**Comment by huangsuyu** [comment]
Hello, @mahsumurebe 


It seems that the limit setting is not enabled. You can try to modify system setting files directly.

**Comment by mahsumurebe** [comment]
Hello, 
I directly changed the system settings files, but there was no change.

*ulimit -a output:*
```
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 31662
max locked memory       (kbytes, -l) 16384
max memory size         (kbytes, -m) unlimited
open files                      (-n) 65535
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 65535
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

*Log:*
```
112573293
panic: open /data/resources/data/application.db/136308125.ldb: too many open files
goroutine 1 [running]:
github.com/tendermint/tendermint/libs/db.(*GoLevelDB).Get(0xc000482c48, 0xc02d690ba0, 0x29, 0x29, 0xc02d760976, 0xc006ee5eb0, 0xc02d690b70)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-tendermint@v0.32.3-binance.3/libs/db/go_level_db.go:56 +0x137
github.com/tendermint/tendermint/libs/db.(*prefixDB).Get(0xc00fdd2fc0, 0xc02d690b70, 0x21, 0x21, 0x0, 0x0, 0x0)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-tendermint@v0.32.3-binance.3/libs/db/prefix_db.go:60 +0x14a
github.com/tendermint/iavl.(*nodeDB).GetNode(0xc00fdd3020, 0xc036efcf80, 0x20, 0x20, 0x0)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-tendermint-iavl@v0.12.0-binance.4/nodedb.go:66 +0x133
github.com/tendermint/iavl.(*Node).getLeftNode(0xc025eb98c0, 0xc01465a300, 0x0, 0x0)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-tendermint-iavl@v0.12.0-binance.4/node.go:387 +0x180
github.com/tendermint/iavl.(*Node).get(0xc025eb98c0, 0xc01465a300, 0xc036efce40, 0x1c, 0x20, 0x1c, 0xffffffffffffffff, 0x142e2c0, 0x10)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-tendermint-iavl@v0.12.0-binance.4/node.go:188 +0x184
github.com/tendermint/iavl.(*Node).get(0xc025eb9800, 0xc01465a300, 0xc036efce40, 0x1c, 0x20, 0x1c, 0xffffffffffffffff, 0x10, 0xc006ee6080)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-tendermint-iavl@v0.12.0-binance.4/node.go:188 +0x1bd
github.com/tendermint/iavl.(*Node).get(0xc03ec67680, 0xc01465a300, 0xc036efce40, 0x1c, 0x20, 0x1c, 0x1, 0x14ccc20, 0x12)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-tendermint-iavl@v0.12.0-binance.4/node.go:188 +0x1bd
github.com/tendermint/iavl.(*Node).get(0xc019a81b00, 0xc01465a300, 0xc036efce40, 0x1c, 0x20, 0x1c, 0xffffffffffffffff, 0x6213, 0x1ad3460)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-tendermint-iavl@v0.12.0-binance.4/node.go:191 +0x256
github.com/tendermint/iavl.(*Node).get(0xc019a803c0, 0xc01465a300, 0xc036efce40, 0x1c, 0x20, 0x1c, 0x1, 0xe, 0x0)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-tendermint-iavl@v0.12.0-binance.4/node.go:188 +0x1bd
github.com/tendermint/iavl.(*Node).get(0xc02ff1dc80, 0xc01465a300, 0xc036efce40, 0x1c, 0x20, 0x1c, 0xffffffffffffffff, 0x142e2c0, 0x145baa0)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-tendermint-iavl@v0.12.0-binance.4/node.go:191 +0x256
github.com/tendermint/iavl.(*Node).get(0xc03c52e900, 0xc01465a300, 0xc036efce40, 0x1c, 0x20, 0x1c, 0xffffffffffffffff, 0xc006ee6270, 0x411496)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-tendermint-iavl@v0.12.0-binance.4/node.go:188 +0x1bd
github.com/tendermint/iavl.(*Node).get(0xc03c52e840, 0xc01465a300, 0xc036efce40, 0x1c, 0x20, 0x1c, 0x1, 0x32927f11, 0x96c9aa31430baf43)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-tendermint-iavl@v0.12.0-binance.4/node.go:188 +0x1bd
github.com/tendermint/iavl.(*Node).get(0xc03c52e780, 0xc01465a300, 0xc036efce40, 0x1c, 0x20, 0x1c, 0x1, 0x20, 0xc036efce40)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-tendermint-iavl@v0.12.0-binance.4/node.go:191 +0x256
github.com/tendermint/iavl.(*Node).get(0xc0001d89c0, 0xc01465a300, 0xc036efce40, 0x1c, 0x20, 0x418c00, 0xc006ee63a8, 0x453832, 0xc036efce40)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-tendermint-iavl@v0.12.0-binance.4/node.go:191 +0x256
github.com/tendermint/iavl.(*ImmutableTree).Get(0xc01465a300, 0xc036efce40, 0x1c, 0x20, 0x20, 0x1448900, 0xc036efce40, 0xc036efce40)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-tendermint-iavl@v0.12.0-binance.4/immutable_tree.go:155 +0x6a
github.com/cosmos/cosmos-sdk/store.(*IavlStore).Get(0xc014660680, 0xc036efce40, 0x1c, 0x20, 0x1c, 0xc036efce40, 0x8)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-cosmos-sdk@v0.25.0-binance.23/store/iavlstore.go:153 +0x4f
github.com/cosmos/cosmos-sdk/x/auth.(*accountStoreCache).GetAccount(0xc0146608e0, 0xc0375db580, 0x14, 0x14, 0x0, 0x0)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-cosmos-sdk@v0.25.0-binance.23/x/auth/mapper.go:236 +0x13d
github.com/cosmos/cosmos-sdk/x/auth.(*accountCache).getAccountFromCache(0xc02f2eee80, 0xc0375db580, 0x14, 0x14, 0x0, 0x102ee64c6)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-cosmos-sdk@v0.25.0-binance.23/x/auth/mapper.go:359 +0x14d
github.com/cosmos/cosmos-sdk/x/auth.(*accountCache).GetAccount(0xc02f2eee80, 0xc0375db580, 0x14, 0x14, 0x1e, 0x3)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-cosmos-sdk@v0.25.0-binance.23/x/auth/mapper.go:299 +0x49
github.com/cosmos/cosmos-sdk/x/auth.AccountKeeper.GetAccount(0x1a931c0, 0xc00048a590, 0x1840be8, 0xc000169650, 0x1aa7740, 0xc0000bc030, 0x1ac0220, 0xc02f2eeec0, 0xa, 0x0, ...)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-cosmos-sdk@v0.25.0-binance.23/x/auth/mapper.go:87 +0x94
github.com/cosmos/cosmos-sdk/x/bank.getCoins(0x1aa7740, 0xc0000bc030, 0x1ac0220, 0xc02f2eeec0, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-cosmos-sdk@v0.25.0-binance.23/x/bank/keeper.go:164 +0xba
github.com/cosmos/cosmos-sdk/x/bank.addCoins(0x1aa7740, 0xc0000bc030, 0x1ac0220, 0xc02f2eeec0, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-cosmos-sdk@v0.25.0-binance.23/x/bank/keeper.go:204 +0xc5
github.com/cosmos/cosmos-sdk/x/bank.BaseKeeper.AddCoins(...)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-cosmos-sdk@v0.25.0-binance.23/x/bank/keeper.go:65
github.com/cosmos/cosmos-sdk/x/stake/keeper.Keeper.Distribute(0x1a931c0, 0xc00048a5f0, 0x1a93200, 0xc00048a7b0, 0xc000169650, 0x1aba9c0, 0xc00029c3e0, 0xc0000d8050, 0x1ac14a0, 0xc0238766e0, ...)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-cosmos-sdk@v0.25.0-binance.23/x/stake/keeper/distribute_sidechain.go:42 +0xff9
github.com/cosmos/cosmos-sdk/x/stake.EndBreatheBlock(0x1aa7740, 0xc0000bc030, 0x1ac0220, 0xc02f2eeec0, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-cosmos-sdk@v0.25.0-binance.23/x/stake/endblock.go:38 +0x60f
github.com/binance-chain/node/app.(*BinanceChain).EndBlocker(0xc0000e4900, 0x1aa7740, 0xc0000bc030, 0x1ac0220, 0xc02f2eeec0, 0xa, 0x0, 0x0, 0x0, 0x0, ...)
        /root/bnbchain/src/github.com/binance-chain/node/app/app.go:817 +0xcc0
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).EndBlock(0xc000370690, 0x6b5bb6d, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-cosmos-sdk@v0.25.0-binance.23/baseapp/baseapp.go:936 +0x12a
github.com/cosmos/cosmos-sdk/server/concurrent.(*asyncLocalClient).EndBlockSync(0xc00029e370, 0x6b5bb6d, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-cosmos-sdk@v0.25.0-binance.23/server/concurrent/async_local_client.go:408 +0x201
github.com/tendermint/tendermint/proxy.(*appConnConsensus).EndBlockSync(0xc025273c60, 0x6b5bb6d, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-tendermint@v0.32.3-binance.3/proxy/app_conn.go:115 +0x51
github.com/tendermint/tendermint/state.execBlockOnProxyApp(0x1aa8b80, 0xc035bb8800, 0x1ab7420, 0xc025273c60, 0xc0409c0000, 0xc010bb8190, 0x1ac33a0, 0xc03ca6c0d0, 0xc039867c20, 0x14, ...)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-tendermint@v0.32.3-binance.3/state/execution.go:298 +0x702
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(0xc035c70620, 0xa, 0x0, 0xc02ec9c0e0, 0x6, 0xc039867c20, 0x14, 0x6b5bb6c, 0x7904c89, 0xc039867c40, ...)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-tendermint@v0.32.3-binance.3/state/execution.go:128 +0x1c2
github.com/tendermint/tendermint/consensus.(*Handshaker).replayBlock(0xc02a0afc80, 0xa, 0x0, 0xc02ec9c0e0, 0x6, 0xc039867c20, 0x14, 0x6b5bb6c, 0x7904c89, 0xc039867c40, ...)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-tendermint@v0.32.3-binance.3/consensus/replay.go:464 +0x258
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc02a0afc80, 0xa, 0x0, 0xc02ec9c0e0, 0x6, 0xc039867c20, 0x14, 0x6b5bb6c, 0x7904c89, 0xc039867c40, ...)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-tendermint@v0.32.3-binance.3/consensus/replay.go:389 +0xda2
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc02a0afc80, 0x1ac5f80, 0xc02b394700, 0x1598060, 0x0)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-tendermint@v0.32.3-binance.3/consensus/replay.go:271 +0x61e
github.com/tendermint/tendermint/node.doHandshake(0x1ac33a0, 0xc03ca6c0d0, 0xa, 0x0, 0xc02ec9c0e0, 0x6, 0xc039867c20, 0x14, 0x6b5bb6c, 0x7904c89, ...)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-tendermint@v0.32.3-binance.3/node/node.go:313 +0x211
github.com/tendermint/tendermint/node.NewNode(0xc0000ce9a0, 0x1aa0480, 0xc040b59040, 0xc00f974a50, 0x1a7e560, 0xc0072de0a0, 0xc00f974c30, 0x1843038, 0xc00f974c40, 0x1aa8b80, ...)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-tendermint@v0.32.3-binance.3/node/node.go:649 +0x497
github.com/cosmos/cosmos-sdk/server.startInProcess(0xc000387440, 0x18439e8, 0x1d, 0x0, 0x0)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-cosmos-sdk@v0.25.0-binance.23/server/start.go:133 +0x57e
github.com/cosmos/cosmos-sdk/server.StartCmd.func1(0xc000b3cf00, 0xc000b39330, 0x0, 0x1, 0x0, 0x0)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-cosmos-sdk@v0.25.0-binance.23/server/start.go:44 +0xb5
github.com/spf13/cobra.(*Command).execute(0xc000b3cf00, 0xc000b39310, 0x1, 0x1, 0xc000b3cf00, 0xc000b39310)
        /root/bnbchain/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x465
github.com/spf13/cobra.(*Command).ExecuteC(0xc00010e000, 0x2, 0xc0003876e0, 0x16cd647)
        /root/bnbchain/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
        /root/bnbchain/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc00010e000, 0x1843e00, 0x2, 0x16a9113)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-tendermint@v0.32.3-binance.3/libs/cli/setup.go:89 +0x3c
main.main()
        /root/bnbchain/src/github.com/binance-chain/node/cmd/bnbchaind/main.go:54 +0x3ef
```

**Comment by mahsumurebe** [comment]
Does anyone have an opinion on this?

**Comment by mahsumurebe** [comment]
Is there any solution to the problem? Anyone have any ideas?

**Comment by rashijzeb** [comment]
Been facing the same issue quite frequently.
Core: 4
RAM: 16GB
Disk: 500GB
Same bnbchain version and ulimit of 65535 for open files.

**Comment by rickyyangz** [comment]
I found a solution from cosmos hub, https://hub.cosmos.network/master/validators/validator-setup.html#problem-2-my-gaiad-crashes-because-of-too-many-open-files

seems if you start bnbchaind by using "systemd", you need to add "LimitNOFILE=4096"

**Comment by rashijzeb** [comment]
> Did you start bnbchaind as a service with "systemd"? If so, you need to add "LimitNOFILE=65535"
> 
> Otherwise, you can change the dbcache config in config.toml
> 
> `open_files_cache_capacity = 1024` -> 500

Have modified open_files_capacity, will monitor for a week atleast and update here. Thanks!

**Comment by mahsumurebe** [comment]
Yes. I started bnbchain as a systemd service. I change the value of LimitNOFILE as you say. I will report the result.
