### ISSUE TITLE
node error

### ISSUE THREAD

**Issue by ares0x** [binance-chain/node-binary#270]
Why am I in such a situation when i upgrade v0.8.2?
system:centos

``` shell
panic: Failed to process committed block (146060001:005749E058B7EB6183775B5E1E2610C3D49A13E7E60C48254CF4ECAB90DD44B9): Wrong Block.Header.AppHash.  Expected 50753935CF80ACF099D5555A7A239C2A88E2B08CE45605265C523F237ACB4116, got EADDD011CB32EE5A7129F1578CAC90DB1D565EBDCFA2E7F96F29B2FCD36955C2

goroutine 538287 [running]:
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc00090b6c0)
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-tendermint@v0.32.3-binance.5/blockchain/v0/reactor.go:404 +0x194b
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
        /root/bnbchain/pkg/mod/github.com/binance-chain/bnc-tendermint@v0.32.3-binance.5/blockchain/v0/reactor.go:127 +0x84
ERROR: error during handshake: error on replay: Wrong Block.Header.AppHash.  Expected 50753935CF80ACF099D5555A7A239C2A88E2B08CE45605265C523F237ACB4116, got EADDD011CB32EE5A7129F1578CAC90DB1D565EBDCFA2E7F96F29B2FCD36955C2
ERROR: error during handshake: error on replay: Wrong Block.Header.AppHash.  Expected 50753935CF80ACF099D5555A7A239C2A88E2B08CE45605265C523F237ACB4116, got EADDD011CB32EE5A7129F1578CAC90DB1D565EBDCFA2E7F96F29B2FCD36955C2

```

**Comment by huangsuyu** [comment]
Hello! did you update `app.toml`?

**Comment by ares0x** [comment]
My mistake! When I upgraded bnbchaind, I forgot to migrate app. Toml!

> Hello! did you update `app.toml`?

My mistake! When I upgraded bnbchaind, I forgot to migrate app.toml!Now the problem has been solved, thank you very much!
